### PR TITLE
added two new button for user to retake test or start a new test

### PR DESCRIPTION
**Pull request by williamssam**
## Describe the changes you've made
- Added an event listener to the retake test button to reset all state and redirect user to the "Start page"
- Reload the page if the new test button is clicked

### Type of change
What sort of change have you made:
- [x]  Bug fix (non-breaking change which fixes an issue)
- [x]  New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?
yes

## Checklist:
- [x]  My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x]  I have commented my code, particularly wherever it was hard to understand.
- [ ]  I have made corresponding changes to the documentation.

## Screenshots (Images)
| Before the changes | After the Changes |
| --- | --- |
| before | after |

### CODE REVIEW

**Comment by prakhartiwari0** [comment]
Hey @williamssam, I appreciate your effort, and the changes you have made are amazing!

However I have noticed a bug, when we RETEST, what happens is that the questions from the New Test and the older Test are stacked on top of each other, and is always adding the new questions in the Results Page, which is making it difficult to check the results of the latest test we took.
What we need is that all the results of the older test to get completely erased and only the results of the latest test to be shown.
**Can you solve this bug?**

**Comment by williamssam** [comment]
> Hey @williamssam, I appreciate your effort, and the changes you have made are amazing!
> 
> However I have noticed a bug, when we RETEST, what happens is that the questions from the New Test and the older Test are stacked on top of each other, and is always adding the new questions in the Results Page, which is making it difficult to check the results of the latest test we took. What we need is that all the results of the older test to get completely erased and only the results of the latest test to be shown. **Can you solve this bug?**
> 
> Happy Contributing!

Yh I

**Comment by williamssam** [comment]
Hi @prakhartiwari0, I solved the bug. Pls check

**Review by prakhartiwari0 — APPROVED** [review]
Seems good now, let's see what bugs we face in the future!

**Pull request merged**
