### PR TITLE
Add Back to Home page button

### PR DESCRIPTION
**Pull request by Jiya55**
## Describe the changes you've made
I have added the home button to the result page

### Type of change
What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?
I have tested it locally on my laptop by using github desktop

## Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.

## Screenshots (Images)
| Before the changes | After the Changes |
| --- | --- |
| image | image |

### CODE REVIEW

**Comment by prakhartiwari0** [comment]
Hi @Jiya55 It's good that you added this feature, they are working but need a few changes that I have mentioned. Also, I have edited the message to make it look better as it was a little messed up, which WILL happen because you are new to open source. Just try to learn Markdown and you will be good to go in writing them as they use Markdown. [Markdownguide.org](https://www.markdownguide.org/) is a good resource that you may check out and learn from.

**Comment by Jiya55** [comment]
Hi, Where can i see the changes that you have mentioned? I am unable to find it

**Comment by prakhartiwari0** [comment]
> Hi, Where can i see the changes that you have mentioned? I am unable to find it

I have commented, please check

| image |
| --- |

**Comment by Jiya55** [comment]
> > Hi, Where can i see the changes that you have mentioned? I am unable to find it
> 
> I have commented, please check
> 
> image
I actually at first tried to do that only. I tried to link it like this-
<a href='\Github\Arito\index.html'> and <a href='index.html'> 
but it didn't work as it became a relative link. So I couldn't understand how to link it so that's why i added the website link

**Comment by Jiya55** [comment]
one way to fix it that i can think of is that all the code should be in the same folder like so - 
image

**Comment by prakhartiwari0** [comment]
Nope you can simply change the href path, why change the file location? @Jiya55

**Comment by Jiya55** [comment]
yeah, i figured it out now, by seeing the already written code. it works if href='../index.html'

**Comment by prakhartiwari0** [comment]
Yup that's what I was asking for @Jiya55!

Congratulations on your first-ever PR, it's your first contribution to Open Source, I hope this journey ahead becomes full of learning and joy. I wish you the best!
Keep it with you, it's great to look at your achievements in future when you hit lows: https://firstpr.me/#jiya55
| -- |
| image |

 
You can share about this on Social Media to meet cool people ;) . The community is incredible and they will support you in your growth.

**Comment by prakhartiwari0** [comment]
I have got a few CSS responsiveness bugs @Jiya55, can you try to solve this? You should use devtools of your browser to get the mobile view of the results page and then solve it. Tell me if you need any help.

**Comment by Jiya55** [comment]
is the button not working in mobile View?

**Comment by prakhartiwari0** [comment]
> So the button is not looking good on a small screen i.e mobile screen? Just want to make sure as i had to search what css responsiveness bug meant and how to fix it.

Yup you got it right

**Comment by Jiya55** [comment]
> > So the button is not looking good on a small screen i.e mobile screen? Just want to make sure as i had to search what css responsiveness bug meant and how to fix it.
> 
> Yup you got it right
ok. but then wouldnt i have to make the whole website be responsive on a smaller screen?

**Comment by Jiya55** [comment]
> > So the button is not looking good on a small screen i.e mobile screen? Just want to make sure as i had to search what css responsiveness bug meant and how to fix it.
> 
> Yup you got it right

So how can i fix that?

**Comment by prakhartiwari0** [comment]
Compressed means that they should not be cluttered, I think you are understanding what I am saying...

**Comment by Jiya55** [comment]
uhmm ok. i'll try to do that, tho as per what i can see on the mobile view, all the buttons are aligned well but the button i made sometimes has extra padding.

**Comment by Jiya55** [comment]
I have tried to fix the responsiveness. Hope it's better

**Comment by prakhartiwari0** [comment]
@Jiya55 Yeah it's better now. I have discovered one more little CSS bug, the button is not resizing when hovered upon. So please solve this one too as all the buttons should have the same behaviour.

#### Screen Recording of the Issue
https://user-images.githubusercontent.com/65062036/221580355-fb672356-1bcf-4dfc-91a9-e9657550ee44.mp4

**Comment by Jiya55** [comment]
ok

**Comment by Jiya55** [comment]
the mixed content check is taking a lot of time, it has been going for the last 10 min, is that normal?

**Comment by Jiya55** [comment]
@prakhartiwari0 I have fixed the bug

**Review by prakhartiwari0 — APPROVED** [review]

**Review by prakhartiwari0 — APPROVED** [review]

**Comment by Jiya55** [comment]
Thank you for merging my PR

**Comment by prakhartiwari0** [comment]
> Thank you for merging my PR

You're welcome Jiya, I got a little busy that's why it took longer than it should, so it should have been merged before. 
It's your hard work and determination, I wish you the best for your journey ahead.

Happy Contributing!

**Pull request merged**
