### PR TITLE
Low and full volume image working

### LINKED ISSUE #83: [FEATURE] Control volume by click on soundicons
**Is your feature request related to a problem? Please describe.**
It will be better if we can have a functionality of controlling the volume using the two sound icons present beside the slider. They can be used to directly make the volume zero or maximum.

**Describe the solution you'd like**
We can make them clickable and attach a function of muting & maximizing the volume to them.

### PR DESCRIPTION
**Pull request by ehsaanchanga**
## Describe the changes
Add functionality to the low-volume and full-volume images by changing volume directly by clicking on those two images

### CODE REVIEW

**Comment by prakhartiwari0** [comment]
@ehsaanchanga Can you please tell me the exact code changes you have done to add this feature it is challenging to find it between so many changes (due to linting and styling changes)?

**Comment by ehsaanchanga** [comment]
@prakhartiwari0  i have just implemented working of low image and full image by creating two functions also got access of audio files and arranged the volume accordingly  see line no 46,48,51,52  main.js

**Comment by prakhartiwari0** [comment]
@ehsaanchanga There are some merge conflicts happening, can you please resolve them?

**Comment by ehsaanchanga** [comment]
resolved

**Comment by prakhartiwari0** [comment]
There are a lot of code formatting done and it's a little hard to check if there are any bugs or issues in the code, I have checked the preview link and things are working nice. I am merging this PR and hope nothing breaks, else we would need to revert back changes. 
Thanks for contribution @ehsaanchanga

**Review by prakhartiwari0 — APPROVED** [review]

**Pull request merged**
