### PR TITLE
prevented the user from entering a number less than 0

### PR DESCRIPTION
**Pull request by williamssam**
## Describe the changes you've made
Added if block to check if the number the user entered for "amount of question" is greater than 56 or less than 1

### Type of change
What sort of change have you made:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.

### CODE REVIEW

**Comment by prakhartiwari0** [comment]
For some reason it's not working @williamssam 
I don't know what changes have you done, can you tell me specifically what are the changes you have made?
Because the whole commit is having many format changes it is making it harder to identify it.

Thanks, Happy Contributing!

**Comment by williamssam** [comment]
> ifically what

I added this if check to getValues function to fix #62 

``
if (amount_of_questions < 1 && amount_of_questions > 56) return
``

**Comment by prakhartiwari0** [comment]
> I added this if check to getValues function to fix #62
> 
> `if (amount_of_questions < 1 && amount_of_questions > 56) return`

I don't know if you could catch this but there is a major flaw in this logic. You are saying that 
Run this code `if` the `amount_of_questions` is less than 1 AND `amount_of_questions` is greater than 56. 

This simply means this code will never run because how can a value be both less than 1 and greater than 56 at the same time? 
This is why when you use the deployed preview of this PR, nothing is fixed.

**Comment by williamssam** [comment]
> > I added this if check to getValues function to fix #62
> > `if (amount_of_questions < 1 && amount_of_questions > 56) return`
> 
> I don't know if you could catch this but there is a major flaw in this logic. You are saying that Run this code `if` the `amount_of_questions` is less than 1 AND `amount_of_questions` is greater than 56.
> 
> This simply means this code will never run because how can a value be both less than 1 and greater than 56 at the same time? This is why when you use the deployed preview of this PR, nothing is fixed.

**Comment by williamssam** [comment]
> > I added this if check to getValues function to fix #62
> > `if (amount_of_questions < 1 && amount_of_questions > 56) return`
> 
> I don't know if you could catch this but there is a major flaw in this logic. You are saying that Run this code `if` the `amount_of_questions` is less than 1 AND `amount_of_questions` is greater than 56.
> 
> This simply means this code will never run because how can a value be both less than 1 and greater than 56 at the same time? This is why when you use the deployed preview of this PR, nothing is fixed.

Oh, I'm so sorry. Thanks

**Comment by prakhartiwari0** [comment]
I think you haven't understood the code yet and that's why making these mistakes. I am also partly responsible for this because I haven't written proper documentation in which I have explained the algorithm used to generate questions. 
The thing is that you need not explicitly write to `amount_of_questions` > 56 because it will be decided on the basis of difficulty level by the program.
We need to close this PR, and I will make complete documentation for developers so that they can understand easily what's really going on.

There are many more issues that are present and will come as the app develops more and more, so you will always have the opportunity to contribute!


Happy Contributing!

**Pull request closed without merging**
