### PR TITLE
Navigate between questions

### PR DESCRIPTION
**Pull request by Teja36**
## Describe the changes you've made
1. Added 2 buttons for navigation in html.
2. Styled them to look as mentioned.
3. Wrote 2 new functions for those 2 buttons
4. Previously, real answer and marks were calculated after each answer submission, thought it would be good to calculate all at once as navigating to previous question and re-submitting the answer is causing re-calculation.

### Type of change
What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### How Has This Been Tested?
Tested it on chrome (latest version).

## Checklist:
- [ ] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.

## Screenshots (Images)
| Before the changes | After the Changes |
| --- | --- |
| image | image |

### CODE REVIEW

**Comment by prakhartiwari0** [comment]
This is an excellent feature!
I will be testing these changes in different scenarios, and then inform you if it needs any changes. 

Thanks for your contribution @Teja36 😄

**Comment by Teja36** [comment]
Cool! Thanks!!!

**Review by prakhartiwari0 — CHANGES_REQUESTED** [review]
I have checked this and got a few issues:
- The question done button is not getting green in color when clicked.
- The Layout of the Question box squeezes on the mobile screen

As you can see these are just styling problems. As far as the functionality is concerned, I haven't got any major issues yet, we need to test more to get more idea about this.

We also need to change the buttons as they are really out of the theme. We need to make them look like other buttons, and custom border-radius to have sketchy look.

**Comment by Teja36** [comment]
> The question done button is not getting green in color when clicked.

This can be fixed by assigning classnames to the **Done!** and **Let's Finish It!!** buttons and changing the classnames according to the state of the test instead of overwriting their styles.

> The Layout of the Question box squeezes on the mobile screen

Oops! didn't test it in mobile. I'll take care of it.

> We also need to change the buttons as they are really out of the theme. We need to make them look like other buttons, and custom border-radius to have sketchy look.

I agree. I am more kind of a developer, I just did the basic styling stuff as I haven't got an eye for design. Just get me some designs and I'll implement in no time.

**Comment by prakhartiwari0** [comment]
@Teja36 Thanks for replying properly, this shows the seriousness of the contributor!

> This can be fixed by assigning classnames to the **Done!** and **Let's Finish It!!** buttons and toggling the classnames according to the state of the test instead of overwriting their styles.
> Oops! didn't test it in mobile. I'll take care of it.

Sure, I will be waiting for your edits and tell me whenever you are done with them.

> I agree. I am more kind of a developer, I just did the basic styling stuff as I haven't got an eye for design. Just get me some designs and I'll implement in no time.

No problem, I will design some buttons according to the design of the website and share them here, png images should work, right?

**Comment by Teja36** [comment]
> No problem, I will design some buttons according to the design of the website and share them here, png images should work, right?

Yep!

**Comment by Teja36** [comment]
> Sure, I will be waiting for your edits and tell me whenever you are done with them.

Done!
* Fixed the submit button color issue.
* Made navigation buttons responsive.

> No problem, I will design some buttons according to the design of the website and share them here, png images should work, right?

Yep!

**Comment by prakhartiwari0** [comment]
That is great!
Thanks for your valuable contribution @Teja36 😇

I will be sharing those little arrow images very soon. After I share them, just put them there and test if it's working properly, and after a few other changes, we will merge these changes into the main branch and release a new version 🥳

**Comment by Teja36** [comment]
>Download, and implement them in the app. Tell me if you face any issues

Are you okay with the size of the buttons?

**Comment by prakhartiwari0** [comment]
yup @Teja36, the size is good, but can you add the click sound when they are clicked? You can use `sound_player("click_sound")` in the part of the code that is executed just after the buttons are clicked. This would improve the UX.

**Comment by Teja36** [comment]
There you go!

**Comment by prakhartiwari0** [comment]
@Teja36 I don't think any more changes are required at this moment, I know you must be thinking why this PR isn't merged yet, so please be patient, it will take some time but this will get merged. I am actually going through a few problems rn but don't worry.

I want to Thank you again for contributing and adding this useful feature 😊

**Comment by prakhartiwari0** [comment]
@Teja36 I don't think any more changes are required at this moment, I know you must be thinking why this PR isn't merged yet, so please be patient, it will take some time but this will get merged. I am actually going through a few problems rn but don't worry.

I want to Thank you again for contributing and adding this useful feature 😊

**Review by prakhartiwari0 — APPROVED** [review]
Everything Seems good as of now, let's see if we face any bug in the future

**Pull request merged**
