### PR TITLE
retake button

### PR DESCRIPTION
**Pull request by jia-ayo**
i added a button that takes you to the restart page

### CODE REVIEW

**Comment by prakhartiwari0** [comment]
Oh God I was just now working on it!
Let me check if it's working!!

**Comment by prakhartiwari0** [comment]
@jia-ayo Hey I just checked the preview, 
Here are some suggestions ->
When the user clicks on the retest button, it should NOT redirect it to main.html, because it will erase all the data and start it from beginning, but RETEST here will mean to take the TEST THE USER GAVE PREVIOUSLY again.

I hope I was able to explain that

**Comment by prakhartiwari0** [comment]
So basically, it would remove the existing elements and make the div with class "start_test_div" visible. However there will many bugs that will come up when doing so, and I am solving them only right now

**Comment by prakhartiwari0** [comment]
As of now, you can RAISE AN ISSUE for this feature, and I will work on that so that you can know what I wanted to say. 
So just go to issues panel and make one!

And Thank you so much for contributing 😇

**Comment by jia-ayo** [comment]
> 

I have to seperste the html elements to do that 
If I can go ahead with that I can separate the html elements so I can pick a page to specificly go to

**Comment by prakhartiwari0** [comment]
> I have to seperste the html elements to do that If I can go ahead with that I can separate the html elements so I can pick a page to specificly go to

Um, I think No that would not be a good option, I am planning to do that by the same method all the other element(s) are removed and made visible by changing the display property of the desired element(s).

**Comment by prakhartiwari0** [comment]
@jia-ayo You should raise an issue about this, it will be better if we discuss everything there

**Pull request closed without merging**
