### PR TITLE
Updating CONTRIBUTING.md file

### PR DESCRIPTION
**Pull request by aswin2108**
Related #12 

Did a complete refactoring of the CONTRIBUTORS.md file. Added some extra subheadings, and some resources and refactored some.

### Type of change
What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### How Has This Been Tested?
All the information added was cross-checked.

## Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.

I am not attaching a screenshot as it was a documentation edit. If wanted I would surely edit it!

### CODE REVIEW

**Comment by aswin2108** [comment]
@prakhartiwari0 what needs to be removed and added!?

**Comment by prakhartiwari0** [comment]
Hey @aswin2108, nice improvements!
I will merge this PR after some more things are added. Don't worry, I will tell you soon what needs to be added.

If you want to know how to write good Contributing Guidelines, **kindly read this [guide by Mozilla Science Lab](https://mozillascience.github.io/working-open-workshop/contributing/)**

Happy Contributing!

**Review by prakhartiwari0 — APPROVED** [review]

**Comment by aswin2108** [comment]
Ok, let me know the things to be added!

**Comment by aswin2108** [comment]
I have made some more changes. I request you to merge this for the time being, as others can keep adding to it in the future. I got fed up with writing documents, so stopping for the time being!

**Comment by aswin2108** [comment]
@prakhartiwari0  It would be great if you could merge/tell me what to add!

**Review by prakhartiwari0 — APPROVED** [review]
Nice improvements!

**Comment by prakhartiwari0** [comment]
Hey, @aswin2108 thanks for contributing to this project! 😇
More points need to be added but I will edit the issue message after a few days once I get time.
Take care

**Pull request merged**
