### PR TITLE
made home page more accessible for key-board users

### PR DESCRIPTION
**Pull request by EngineerHamziey**
Hello, thanks for giving us the opportunity to contribute to your open source project.
In this first contrubution of mine, my intention is to make this home page accessible to keyboard users by adding a focus-visible states, because those using the tab key to navigate sites will know which link they are on. [here is a preview](https://arito-accessibility-preview.netlify.app/), ensure to navigate throught the tab key to see the state.

From [mdn web doc](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) **"Make sure the visual focus indicator can be seen by people with low vision. This will also benefit anyone use a screen in a brightly lit space (like outside in the sun). [WCAG 2.1 SC 1.4.11 Non-Text Contrast](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html) requires that the visual focus indicator be at least 3 to 1."**

Hopefully very soon I'll add more effort to make it more accessible. Feel Free to correct me, I also a beginer when it comes to web content accessiblity.

### CODE REVIEW

**Comment by prakhartiwari0** [comment]
This is an amazing contribution @EngineerHamziey! I will soon be reviewing this PR and inform you if any changes are needed.
You are doing a great job, 
Happy Contributing 😊

**Comment by EngineerHamziey** [comment]
> This is an amazing contribution @EngineerHamziey! I will soon be reviewing this PR and inform you if any changes are needed. You are doing a great job, Happy Contributing 😊

Thanks so much, I'll love to hear from you soon

**Review by prakhartiwari0 — APPROVED** [review]
Very Useful contribution, we should take care of the accessibility part more so that this app can also be used by differently-abled children and adults!

**Comment by prakhartiwari0** [comment]
I would love to have more contributions like this from you @EngineerHamziey

**Pull request merged**
