### PR TITLE
Fix one typo

### PR DESCRIPTION
**Pull request by EmmanuelEngelbert**
Improved the grammar of the readme file. 
Changed the word 'arithematic' to 'arithmetic' in the About Arito section.

## Describe the changes you've made
Made an improvement to the grammar of the About Arito section

### Type of change
What sort of change have you made:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?
Ran a spell check on the About Arito Section

## Checklist:
- [x] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.

Here is a picture of the original About Arito section 
Screenshot 2022-11-19 at 09 54 02

Here is a picture of the About Arito section after the change to the readme file
Screenshot 2022-11-19 at 09 55 24

### CODE REVIEW

**Comment by prakhartiwari0** [comment]
Very small typo, no problem I am merging this PR but make sure to make a legible Pull Request which makes some more changes to the project and not just fixes ONE TYPO. 😅 For very small changes, just comment on that issue about it.

Please also link the issue to this PR by putting #issue_number in the heading, I am editing it from my side, keep it in mind for the future. 😄

**Comment by prakhartiwari0** [comment]
Also, make sure not to work and create PR for issues you are not assigned. You should talk to the assignee first or if there is no assignee, ask the maintainer (in this case me) to make you the assignee for that issue.

**Comment by EmmanuelEngelbert** [comment]
Hi @prakhartiwari0 first of all I would like to thank you for giving such detailed feedback. I will reflect on the advice you have given me and I would love to know the type of edits you made to make the PR I raised legible. 
You are are great person so I would like to stay around to make more meaningful contributions to the project. Thank you!

**Comment by prakhartiwari0** [comment]
Thanks for your positive feedback and contributions @EmmanuelEngelbert ! 
You are doing a great job and being helpful 😊
Would love to be connected with you.

### Type of Edits I have made to your PR
Nothing much, I just changed the title from Improve Readme file to Fix One Typo, as it is important that the title should tell what exactly is this PR for. 
The second change is also very small, I just replaced the <issue_number> in the PR with issue #3 because it was for that issue only. In GitHub we can give reference to Issues and PRs through this simple method, you can read more about it in these two places -
- [Auto Linked References](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls#issues-and-pull-requests)
- [Linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

**Comment by EmmanuelEngelbert** [comment]
Thanks to your explanation I now have a clearer idea on the subject of PRs. 
Sure, I'd love to connect!

**Pull request merged**
