### PR TITLE
Add a sound controller

### LINKED ISSUE #13: [FEATURE] Add Sound/Music/Volume Buttons
**Is your feature request related to a problem? Please describe.**
Sometimes we want to stop the background music or the sounds of button clicks of the app but not decrease the volume of our device. This leads to irritation because there is no option for mute/unmute sounds or volume control in the app itself

**Describe the solution you'd like**
It would be handy if the app itself contains buttons to disable/enable music/sounds. 
Adding a volume control button will also be good.

**Additional context**
| image |  |
| --- | --- |

### PR DESCRIPTION
**Pull request by Daniel53245**
## Describe the changes you've made
Add a volume controller on the website that sticks at the bottom.

### Type of change
What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?
I went through the test serval time and the volume controller works well

## Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.

### CODE REVIEW

**Comment by prakhartiwari0** [comment]
@Daniel53245 Kindly edit the Pull request and write the section where you need to Describe what changes you have done.

**Comment by prakhartiwari0** [comment]
There are a lot of bugs currently, please also include recordings for proper analysis of the changes. 

One bug I have got is that we cannot move forward after start the test, there are some errors that appear in the console when click on Start The test button -
image

**Comment by prakhartiwari0** [comment]
But this new feature is really great! **I appreciate your hard work**, it's functioning really well and of course, have some bugs as every code does have them, we need to solve these bugs together!

**Comment by Daniel53245** [comment]
Thanks, I am not keep testing it to see how those error are triggered

**Comment by prakhartiwari0** [comment]
Great Job @Daniel53245 !!
I am just testing it out from my side, on Chrome mobile, and on Brave & Firefox Desktop. Will tell you if I find any issues.

**Comment by prakhartiwari0** [comment]
And yeah I forgot to assign you this issue, sorry for that

**Comment by prakhartiwari0** [comment]
Hey @Daniel53245 what if we keep the controller at the bottom and not make it position fixed which results in it being overlayed over other elements. I think it would be good for UX don't you think so?

**Comment by prakhartiwari0** [comment]
And yeah I tested it, everything is working fine as per my tests. I am looking for some cross browser testing tools to test the app on various engines from one computer.

**Comment by Daniel53245** [comment]
> Hey @Daniel53245 what if we keep the controller at the bottom and not make it position fixed which results in it being overlayed over other elements? I think it would be good for UX don't you think so?

Yes, it is a good idea. We have to be careful while we are using elements that overlay at fixed positions. I might overload the user with redundant information.

From my perspective, it would be better to keep it fixed position. The volume slider is pretty tiny and will not likely disturb reading the content. 

Moreover, if the application grows larger, the user would have to scroll back and forward to adjust the volume.  Many web pages also use this kind of design for settings and volume. An example would be google. 
msedge_1EAPrlbarr
As you could see in the above image they have the setting and the content you searched at the top.

Another reason that I put it at the bottom right is that the volume control on the windows system is at the bottom right of the screen. If someone feels that it is too loud, they would naturally move their mouse to the bottom right noticing the volume slider we provide.

Overall, I really hope that we could keep the volume slider at its current position. It is convenient for the user using the software. Moreover, we could do some further operations to design the graphic of the slider or try to hide it when unnecessary.

**Comment by prakhartiwari0** [comment]
I understand your points, **on Desktop, there is no problem with that**, 
but when we open the app on mobile, this happens-
| Screenshot from 2022-11-21 09-19-18 | Screenshot from 2022-11-21 09-19-55 |
| --- | --- |

And because **we are targeting both mobile and desktop users**, this app needs to have good UI/UX for both devices. Also, we are using the mobile-first approach in Styling if you had noticed.
And therefore I was making the point of keeping it at the bottom. Because the app is not so long in terms of height, mobile users will not have any problem scrolling down. In fact, they need to scroll for volume only on the TEST FORM page and RESULTS page.
And the example of google might not be a good one here, because the only thing (at least the main task) we do at google is to **search**, and therefore it makes sense for them to make the search bar stick on the top so that the user doesn't need to scroll up the long Results Page (the Results page is long in terms of height) to use the search bar, which improves UX a lot.
If you go to [DuckDuckGo](https://duckduckgo.com/), they haven't made the search bar stick to the top, which makes it quite 
**annoying** to go to the top again and again just to search. (I have used DuckDuckGo's example just to explain)

But in our case, the volume button **is just a feature** and not the main element with which the user will be interacting most of the time, therefore `keeping it at the bottom and not making it appear every time on top of other elements`, makes sense.

I hope I was able to briefly explain my points, if you have any other points regarding the UI/UX **I would be glad to know them!**

**Comment by Daniel53245** [comment]
j1EdjNaJw5
Hi, I just made the change on the repo. Thank you for pointing out that the design is a problem for screens with different ratios. Sorry for the inconvenience. Now the controller is outside the area the user interacts with the application.

**Comment by prakhartiwari0** [comment]
So once I set up all of that, I will merge this PR which will make a new version of this app!

**Comment by prakhartiwari0** [comment]
I once again want to appreciate your efforts and thanks for contributing to this project! 
I hope you contribute more and make this open-source project a lot better 😄

**Comment by prakhartiwari0** [comment]
Hey @Daniel53245 please add a `.gitignore` file and write `.DS_Store` inside it. This file is coming with your PR and is not required. I guess it is a Mac config file or something.

**Review by prakhartiwari0 — APPROVED** [review]
This feature is Amazing! Thanks to @Daniel53245 for making this contribution to the project.

**Pull request merged**
