### PR TITLE
Added pull request template

### LINKED ISSUE #187: Missing Pull Request template
Pull Request Template means when someone opens a Pull Request, they will have a template that they can edit making it easier for maintainers of the project to review PR and make sure that no PR is submitted without proper description.

Please assign this issue to me under GSSoC'23
@prakhartiwari0

### PR DESCRIPTION
**Pull request by DivyanshiNarang**
Closes #187 

Addition of pull request template in .yml format.

@prakhartiwari0 Please review this PR.

### CODE REVIEW

**Review by gambhirsharma — APPROVED** [review]
Looks good 👍

**Comment by gambhirsharma** [comment]
PR merged! Well done on your contribution!

**Comment by gambhirsharma** [comment]
It's not working as expected
Screenshot 2023-07-04 at 12 25 11 AM (2)

**Comment by DivyanshiNarang** [comment]
Hey @gambhirsharma, should I create another PR for resolving this issue.

**Comment by gambhirsharma** [comment]
> Hey @gambhirsharma, should I create another PR for resolving this issue.

Yes, make a new PR with a new branch. 

Read the official Documentation properly.

**Comment by DivyanshiNarang** [comment]
@gambhirsharma Sorry for the inconvenience caused. I have created a new PR with a new branch.

**Pull request merged**
