### PR TITLE
Contributions

### PR DESCRIPTION
**Pull request by Kasambx**
Added new screenshots 
Added some more description about the web application. 
Added some description on the contributors section.
Changed the positioning of the screenshots

### CODE REVIEW

**Review by Kasambx — COMMENTED** [review]
Added more screenshots 
Added more about the project 
Corrected grammatical mistakes 
Added more info on the contributors section.
Changed the positioning of the screenshots

**Review by prakhartiwari0 — CHANGES_REQUESTED** [review]
There are a few typos and incorrect language used, kindly correct all of them and commit your changes. 
Happy Contributing! 😇

**Review by prakhartiwari0 — APPROVED** [review]
Nice little changes

**Comment by prakhartiwari0** [comment]
Hope you contribute more to this project!
Thank you 😊

**Pull request merged**
